unit hal;

interface

const
  XTHAL_RELEASE_MAJOR_const = 8000;
  XTHAL_RELEASE_MINOR_const = 1;
  XTHAL_RELEASE_NAME_const = '8.0.1';
  XTHAL_REL_8 = 1;
  XTHAL_REL_8_0 = 1;
  XTHAL_REL_8_0_1 = 1;
  XTHAL_MAJOR_REV = XTHAL_RELEASE_MAJOR_const;
  XTHAL_MINOR_REV = XTHAL_RELEASE_MINOR_const;
  XTHAL_PREFETCH_ENABLE = -(1);
  XTHAL_PREFETCH_DISABLE = 0;
  XTHAL_MAYBE = -(1);
  XTHAL_MAX_CPS = 8;
  XTHAL_LITTLEENDIAN = 0;
  XTHAL_BIGENDIAN = 1;
  XTHAL_DISASM_BUFSIZE = 80;
  XTHAL_DISASM_OPT_ADDR = $0001;
  XTHAL_DISASM_OPT_OPHEX = $0002;
  XTHAL_DISASM_OPT_OPCODE = $0004;
  XTHAL_DISASM_OPT_PARMS = $0008;
  XTHAL_DISASM_OPT_ALL = $0FFF;
  XTHAL_MAX_INTERRUPTS = 32;
  XTHAL_MAX_INTLEVELS = 16;
  XTHAL_MAX_TIMERS = 4;
  XTHAL_INTTYPE_UNCONFIGURED = 0;
  XTHAL_INTTYPE_SOFTWARE = 1;
  XTHAL_INTTYPE_EXTERN_EDGE = 2;
  XTHAL_INTTYPE_EXTERN_LEVEL = 3;
  XTHAL_INTTYPE_TIMER = 4;
  XTHAL_INTTYPE_NMI = 5;
  XTHAL_INTTYPE_WRITE_ERROR = 6;
  XTHAL_MAX_INTTYPES = 7;
  XTHAL_TIMER_UNCONFIGURED = -(1);
  XTHAL_TIMER_UNASSIGNED = XTHAL_TIMER_UNCONFIGURED;
  XTHAL_MEMEP_PARITY = 1;
  XTHAL_MEMEP_ECC = 2;
  XTHAL_MEMEP_F_LOCAL = 0;
  XTHAL_MEMEP_F_DCACHE_DATA = 4;
  XTHAL_MEMEP_F_DCACHE_TAG = 5;
  XTHAL_MEMEP_F_ICACHE_DATA = 6;
  XTHAL_MEMEP_F_ICACHE_TAG = 7;
  XTHAL_MEMEP_F_CORRECTABLE = 16;
  XTHAL_AMB_EXCEPTION = 0;
  XTHAL_AMB_HITCACHE = 1;
  XTHAL_AMB_ALLOCATE = 2;
  XTHAL_AMB_WRITETHRU = 3;
  XTHAL_AMB_ISOLATE = 4;
  XTHAL_AMB_GUARD = 5;
  XTHAL_AMB_COHERENT = 6;
  XTHAL_AM_EXCEPTION = 1 shl XTHAL_AMB_EXCEPTION;
  XTHAL_AM_HITCACHE = 1 shl XTHAL_AMB_HITCACHE;
  XTHAL_AM_ALLOCATE = 1 shl XTHAL_AMB_ALLOCATE;
  XTHAL_AM_WRITETHRU = 1 shl XTHAL_AMB_WRITETHRU;
  XTHAL_AM_ISOLATE = 1 shl XTHAL_AMB_ISOLATE;
  XTHAL_AM_GUARD = 1 shl XTHAL_AMB_GUARD;
  XTHAL_AM_COHERENT = 1 shl XTHAL_AMB_COHERENT;
  XTHAL_FAM_EXCEPTION = $001;
  XTHAL_FAM_BYPASS = $000;
  XTHAL_FAM_CACHED = $006;
  XTHAL_LAM_EXCEPTION = $001;
  XTHAL_LAM_ISOLATE = $012;
  XTHAL_LAM_BYPASS = $000;
  XTHAL_LAM_BYPASSG = $020;
  XTHAL_LAM_CACHED_NOALLOC = $002;
  XTHAL_LAM_NACACHED = XTHAL_LAM_CACHED_NOALLOC;
  XTHAL_LAM_NACACHEDG = $022;
  XTHAL_LAM_CACHED = $006;
  XTHAL_LAM_COHCACHED = $046;
  XTHAL_SAM_EXCEPTION = $001;
  XTHAL_SAM_ISOLATE = $032;
  XTHAL_SAM_BYPASS = $028;
  XTHAL_SAM_WRITETHRU = $02A;
  XTHAL_SAM_WRITEBACK = $026;
  XTHAL_SAM_COHWRITEBACK = $066;
  XTHAL_SAM_WRITEBACK_NOALLOC = $022;
  XTHAL_CAFLAG_EXPAND = $000100;
  XTHAL_CAFLAG_EXACT = $000200;
  XTHAL_CAFLAG_NO_PARTIAL = $000400;
  XTHAL_CAFLAG_NO_AUTO_WB = $000800;
  XTHAL_CAFLAG_NO_AUTO_INV = $001000;
{$ifdef INCLUDE_DEPRECATED_HAL_DEBUG_CODE}
  XTHAL_24_BIT_BREAK = $80000000;
  XTHAL_16_BIT_BREAK = $40000000;
  XTHAL_DEST_REG = $f0000000;
  XTHAL_DEST_REG_INST = $08000000;
  XTHAL_DEST_REL_INST = $04000000;
  XTHAL_RFW_INST = $00000800;
  XTHAL_RFUE_INST = $00000400;
  XTHAL_RFI_INST = $00000200;
  XTHAL_RFE_INST = $00000100;
  XTHAL_RET_INST = $00000080;
  XTHAL_BREAK_INST = $00000040;
  XTHAL_SYSCALL_INST = $00000020;
  XTHAL_LOOP_END = $00000010;
  XTHAL_JUMP_INST = $00000008;
  XTHAL_BRANCH_INST = $00000004;
  XTHAL_24_BIT_INST = $00000002;
  XTHAL_16_BIT_INST = $00000001;
{$endif}

type
  TXtHalVoidFunc = procedure();
  PXtHalVoidFunc = ^TXtHalVoidFunc;

// Macro alias...
function xthal_get_intread: uint32; external name 'xthal_get_interrupt';

procedure xthal_save_extra(base: pointer); cdecl; external;
procedure xthal_restore_extra(base: pointer); cdecl; external;
procedure xthal_save_cpregs(base: pointer; para2: longint); cdecl; external;
procedure xthal_restore_cpregs(base: pointer; para2: longint); cdecl; external;
procedure xthal_save_cp0(base: pointer); cdecl; external;
procedure xthal_save_cp1(base: pointer); cdecl; external;
procedure xthal_save_cp2(base: pointer); cdecl; external;
procedure xthal_save_cp3(base: pointer); cdecl; external;
procedure xthal_save_cp4(base: pointer); cdecl; external;
procedure xthal_save_cp5(base: pointer); cdecl; external;
procedure xthal_save_cp6(base: pointer); cdecl; external;
procedure xthal_save_cp7(base: pointer); cdecl; external;
procedure xthal_restore_cp0(base: pointer); cdecl; external;
procedure xthal_restore_cp1(base: pointer); cdecl; external;
procedure xthal_restore_cp2(base: pointer); cdecl; external;
procedure xthal_restore_cp3(base: pointer); cdecl; external;
procedure xthal_restore_cp4(base: pointer); cdecl; external;
procedure xthal_restore_cp5(base: pointer); cdecl; external;
procedure xthal_restore_cp6(base: pointer); cdecl; external;
procedure xthal_restore_cp7(base: pointer); cdecl; external;
procedure xthal_init_mem_extra(para1: pointer); cdecl; external;
procedure xthal_init_mem_cp(para1: pointer; para2: longint); cdecl; external;
procedure xthal_icache_region_invalidate(addr: pointer; size: dword); cdecl; external;
procedure xthal_dcache_region_invalidate(addr: pointer; size: dword); cdecl; external;
procedure xthal_icache_line_invalidate(addr: pointer); cdecl; external;
procedure xthal_dcache_line_invalidate(addr: pointer); cdecl; external;
procedure xthal_dcache_region_writeback(addr: pointer; size: dword); cdecl; external;
procedure xthal_dcache_line_writeback(addr: pointer); cdecl; external;
procedure xthal_dcache_region_writeback_inv(addr: pointer; size: dword); cdecl; external;
procedure xthal_dcache_line_writeback_inv(addr: pointer); cdecl; external;
procedure xthal_icache_sync; cdecl; external;
procedure xthal_dcache_sync; cdecl; external;
procedure xthal_cache_coherence_on; cdecl; external;
procedure xthal_cache_coherence_off; cdecl; external;
procedure xthal_cache_coherence_optin; cdecl; external;
procedure xthal_cache_coherence_optout; cdecl; external;
function xthal_set_cache_prefetch(para1: longint): longint; cdecl; external;
function xthal_get_cache_prefetch: longint; cdecl; external;
function xthal_set_soft_break(addr: pointer): dword; cdecl; external;
procedure xthal_remove_soft_break(addr: pointer; para2: dword); cdecl; external;
function xthal_disassemble(instr_buf: Pbyte; tgt_addr: pointer; buffer: PChar;
  buflen: dword; options: dword): longint; cdecl; external;
function xthal_disassemble_size(instr_buf: Pbyte): longint; cdecl; external;
function xthal_memcpy(dst: pointer; src: pointer; len: dword): pointer; cdecl; external;
function xthal_bcopy(src: pointer; dst: pointer; len: dword): pointer; cdecl; external;
function xthal_compare_and_set(addr: Plongint; test_val: longint;
  compare_val: longint): longint; cdecl; external;
procedure xthal_window_spill; cdecl; external;
procedure xthal_validate_cp(para1: longint); cdecl; external;
procedure xthal_invalidate_cp(para1: longint); cdecl; external;
procedure xthal_set_cpenable(para1: dword); cdecl; external;
function xthal_get_cpenable: dword; cdecl; external;
function xthal_get_intenable: dword; cdecl; external;
procedure xthal_set_intenable(para1: dword); cdecl; external;
function xthal_get_interrupt: dword; cdecl; external;
procedure xthal_set_intset(para1: dword); cdecl; external;
procedure xthal_set_intclear(para1: dword); cdecl; external;
function xthal_get_ccount: dword; cdecl; external;
procedure xthal_set_ccompare(para1: longint; para2: dword); cdecl; external;
function xthal_get_ccompare(para1: longint): dword; cdecl; external;
function xthal_get_prid: dword; cdecl; external;
function xthal_vpri_to_intlevel(vpri: dword): dword; cdecl; external;
function xthal_intlevel_to_vpri(intlevel: dword): dword; cdecl; external;
function xthal_int_enable(para1: dword): dword; cdecl; external;
function xthal_int_disable(para1: dword): dword; cdecl; external;
function xthal_set_int_vpri(intnum: longint; vpri: longint): longint; cdecl; external;
function xthal_get_int_vpri(intnum: longint): longint; cdecl; external;
procedure xthal_set_vpri_locklevel(intlevel: dword); cdecl; external;
function xthal_get_vpri_locklevel: dword; cdecl; external;
function xthal_set_vpri(vpri: dword): dword; cdecl; external;
function xthal_get_vpri: dword; cdecl; external;
function xthal_set_vpri_intlevel(intlevel: dword): dword; cdecl; external;
function xthal_set_vpri_lock: dword; cdecl; external;
function xthal_tram_pending_to_service: dword; cdecl; external;
procedure xthal_tram_done(serviced_mask: dword); cdecl; external;
function xthal_tram_set_sync(intnum: longint; sync: longint): longint; cdecl; external;
function xthal_set_tram_trigger_func(trigger_fn: PXtHalVoidFunc): PXtHalVoidFunc;
  cdecl; external;
function xthal_get_cacheattr: dword; cdecl; external;
function xthal_get_icacheattr: dword; cdecl; external;
function xthal_get_dcacheattr: dword; cdecl; external;
procedure xthal_set_cacheattr(para1: dword); cdecl; external;
procedure xthal_set_icacheattr(para1: dword); cdecl; external;
procedure xthal_set_dcacheattr(para1: dword); cdecl; external;
function xthal_set_region_attribute(addr: pointer; size: dword;
  cattr: dword; flags: dword): longint; cdecl; external;
procedure xthal_icache_enable; cdecl; external;
procedure xthal_dcache_enable; cdecl; external;
procedure xthal_icache_disable; cdecl; external;
procedure xthal_dcache_disable; cdecl; external;
procedure xthal_icache_all_invalidate; cdecl; external;
procedure xthal_dcache_all_invalidate; cdecl; external;
procedure xthal_dcache_all_writeback; cdecl; external;
procedure xthal_dcache_all_writeback_inv; cdecl; external;
procedure xthal_icache_region_lock(addr: pointer; size: dword); cdecl; external;
procedure xthal_dcache_region_lock(addr: pointer; size: dword); cdecl; external;
procedure xthal_icache_line_lock(addr: pointer); cdecl; external;
procedure xthal_dcache_line_lock(addr: pointer); cdecl; external;
procedure xthal_icache_all_unlock; cdecl; external;
procedure xthal_dcache_all_unlock; cdecl; external;
procedure xthal_icache_region_unlock(addr: pointer; size: dword); cdecl; external;
procedure xthal_dcache_region_unlock(addr: pointer; size: dword); cdecl; external;
procedure xthal_icache_line_unlock(addr: pointer); cdecl; external;
procedure xthal_dcache_line_unlock(addr: pointer); cdecl; external;
procedure xthal_memep_inject_error(addr: pointer; size: longint;
  flags: longint); cdecl; external;
function xthal_static_v2p(vaddr: dword; paddrp: Pdword): longint; cdecl; external;
function xthal_static_p2v(paddr: dword; vaddrp: Pdword; cached: dword): longint;
  cdecl; external;

{$ifdef INCLUDE_DEPRECATED_HAL_DEBUG_CODE}
type
  Pxthal_state = ^Txthal_state;
  Txthal_state = record
    pc: dword;
    ar: array[0..15] of dword;
    lbeg: dword;
    lend: dword;
    lcount: dword;
    extra_ptr: dword;
    cpregs_ptr: array[0..(XTHAL_MAX_CPS) - 1] of dword;
  end;

function xthal_inst_type(addr: pointer): dword; cdecl; external;
function xthal_branch_addr(addr: pointer): dword; cdecl; external;
function xthal_get_npc(user_state: PXTHAL_STATE): dword; cdecl; external;
{$endif}

var
  Xthal_debug_configured : longint;cvar;external;
  Xthal_rev_no : dword;cvar;external;
  Xthal_cpregs_save_fn : array[0..(XTHAL_MAX_CPS)-1] of pointer;cvar;external;
  Xthal_cpregs_restore_fn : array[0..(XTHAL_MAX_CPS)-1] of pointer;cvar;external;
  Xthal_cpregs_save_nw_fn : array[0..(XTHAL_MAX_CPS)-1] of pointer;cvar;external;
  Xthal_cpregs_restore_nw_fn : array[0..(XTHAL_MAX_CPS)-1] of pointer;cvar;external;
  Xthal_extra_size : dword;cvar;external;
  Xthal_extra_align : dword;cvar;external;
  Xthal_cpregs_size : array[0..(XTHAL_MAX_CPS)-1] of dword;cvar;external;
  Xthal_cpregs_align : array[0..(XTHAL_MAX_CPS)-1] of dword;cvar;external;
  Xthal_all_extra_size : dword;cvar;external;
  Xthal_all_extra_align : dword;cvar;external;
  Xthal_cp_names : array[0..(XTHAL_MAX_CPS)-1] of Pchar;cvar;external;
  Xthal_num_coprocessors : dword;cvar;external;
  Xthal_cp_num : byte;cvar;external;
  Xthal_cp_max : byte;cvar;external;
  Xthal_cp_mask : dword;cvar;external;
  Xthal_num_aregs : dword;cvar;external;
  Xthal_num_aregs_log2 : byte;cvar;external;
  Xthal_icache_linewidth : byte;cvar;external;
  Xthal_dcache_linewidth : byte;cvar;external;
  Xthal_icache_linesize : word;cvar;external;
  Xthal_dcache_linesize : word;cvar;external;
  Xthal_icache_size : dword;cvar;external;
  Xthal_dcache_size : dword;cvar;external;
  Xthal_dcache_is_writeback : byte;cvar;external;
  Xthal_release_major : dword;cvar;external;
  Xthal_release_minor : dword;cvar;external;
  Xthal_release_name : Pchar;cvar;external;
  Xthal_release_internal : Pchar;cvar;external;
  Xthal_memory_order : byte;cvar;external;
  Xthal_have_windowed : byte;cvar;external;
  Xthal_have_density : byte;cvar;external;
  Xthal_have_booleans : byte;cvar;external;
  Xthal_have_loops : byte;cvar;external;
  Xthal_have_nsa : byte;cvar;external;
  Xthal_have_minmax : byte;cvar;external;
  Xthal_have_sext : byte;cvar;external;
  Xthal_have_clamps : byte;cvar;external;
  Xthal_have_mac16 : byte;cvar;external;
  Xthal_have_mul16 : byte;cvar;external;
  Xthal_have_fp : byte;cvar;external;
  Xthal_have_speculation : byte;cvar;external;
  Xthal_have_threadptr : byte;cvar;external;
  Xthal_have_pif : byte;cvar;external;
  Xthal_num_writebuffer_entries : word;cvar;external;
  Xthal_build_unique_id : dword;cvar;external;
  Xthal_hw_configid0 : dword;cvar;external;
  Xthal_hw_configid1 : dword;cvar;external;
  Xthal_hw_release_major : dword;cvar;external;
  Xthal_hw_release_minor : dword;cvar;external;
  Xthal_hw_release_name : Pchar;cvar;external;
  Xthal_hw_release_internal : Pchar;cvar;external;
  Xthal_num_intlevels : byte;cvar;external;
  Xthal_num_interrupts : byte;cvar;external;
  Xthal_intlevel_mask : array[0..(XTHAL_MAX_INTLEVELS)-1] of dword;cvar;external;
  Xthal_intlevel_andbelow_mask : array[0..(XTHAL_MAX_INTLEVELS)-1] of dword;cvar;external;
  Xthal_intlevel : array[0..(XTHAL_MAX_INTERRUPTS)-1] of byte;cvar;external;
  Xthal_inttype : array[0..(XTHAL_MAX_INTERRUPTS)-1] of byte;cvar;external;
  Xthal_inttype_mask : array[0..(XTHAL_MAX_INTTYPES)-1] of dword;cvar;external;
  Xthal_timer_interrupt : array[0..(XTHAL_MAX_TIMERS)-1] of longint;cvar;external;
  Xthal_num_ibreak : longint;cvar;external;
  Xthal_num_dbreak : longint;cvar;external;
  Xthal_have_ccount : byte;cvar;external;
  Xthal_num_ccompare : byte;cvar;external;
  Xthal_have_prid : byte;cvar;external;
  Xthal_have_exceptions : byte;cvar;external;
  Xthal_xea_version : byte;cvar;external;
  Xthal_have_interrupts : byte;cvar;external;
  Xthal_have_highlevel_interrupts : byte;cvar;external;
  Xthal_have_nmi : byte;cvar;external;
  Xthal_tram_pending : dword;cvar;external;
  Xthal_tram_enabled : dword;cvar;external;
  Xthal_tram_sync : dword;cvar;external;
  Xthal_num_instrom : byte;cvar;external;
  Xthal_num_instram : byte;cvar;external;
  Xthal_num_datarom : byte;cvar;external;
  Xthal_num_dataram : byte;cvar;external;
  Xthal_num_xlmi : byte;cvar;external;
  Xthal_instrom_vaddr : Pdword;cvar;external;
  Xthal_instrom_paddr : Pdword;cvar;external;
  Xthal_instrom_size : Pdword;cvar;external;
  Xthal_instram_vaddr : Pdword;cvar;external;
  Xthal_instram_paddr : Pdword;cvar;external;
  Xthal_instram_size : Pdword;cvar;external;
  Xthal_datarom_vaddr : Pdword;cvar;external;
  Xthal_datarom_paddr : Pdword;cvar;external;
  Xthal_datarom_size : Pdword;cvar;external;
  Xthal_dataram_vaddr : Pdword;cvar;external;
  Xthal_dataram_paddr : Pdword;cvar;external;
  Xthal_dataram_size : Pdword;cvar;external;
  Xthal_xlmi_vaddr : Pdword;cvar;external;
  Xthal_xlmi_paddr : Pdword;cvar;external;
  Xthal_xlmi_size : Pdword;cvar;external;
  Xthal_icache_setwidth : byte;cvar;external;
  Xthal_dcache_setwidth : byte;cvar;external;
  Xthal_icache_ways : dword;cvar;external;
  Xthal_dcache_ways : dword;cvar;external;
  Xthal_icache_line_lockable : byte;cvar;external;
  Xthal_dcache_line_lockable : byte;cvar;external;
  Xthal_have_spanning_way : byte;cvar;external;
  Xthal_have_identity_map : byte;cvar;external;
  Xthal_have_mimic_cacheattr : byte;cvar;external;
  Xthal_have_xlt_cacheattr : byte;cvar;external;
  Xthal_have_cacheattr : byte;cvar;external;
  Xthal_have_tlbs : byte;cvar;external;
  Xthal_mmu_asid_bits : byte;cvar;external;
  Xthal_mmu_asid_kernel : byte;cvar;external;
  Xthal_mmu_rings : byte;cvar;external;
  Xthal_mmu_ring_bits : byte;cvar;external;
  Xthal_mmu_sr_bits : byte;cvar;external;
  Xthal_mmu_ca_bits : byte;cvar;external;
  Xthal_mmu_max_pte_page_size : dword;cvar;external;
  Xthal_mmu_min_pte_page_size : dword;cvar;external;
  Xthal_itlb_way_bits : byte;cvar;external;
  Xthal_itlb_ways : byte;cvar;external;
  Xthal_itlb_arf_ways : byte;cvar;external;
  Xthal_dtlb_way_bits : byte;cvar;external;
  Xthal_dtlb_ways : byte;cvar;external;
  Xthal_dtlb_arf_ways : byte;cvar;external;
  {$ifdef INCLUDE_DEPRECATED_HAL_CODE}
    Xthal_have_old_exc_arch : byte;cvar;external;
    Xthal_have_mmu : byte;cvar;external;
    Xthal_num_regs : dword;cvar;external;
    Xthal_num_iroms : byte;cvar;external;
    Xthal_num_irams : byte;cvar;external;
    Xthal_num_droms : byte;cvar;external;
    Xthal_num_drams : byte;cvar;external;
    Xthal_configid0 : dword;cvar;external;
    Xthal_configid1 : dword;cvar;external;
  {$endif}
  {$ifdef INCLUDE_DEPRECATED_HAL_DEBUG_CODE}
    Xthal_ill_inst_16 : array[0..15] of word;cvar;external;
  {$endif}

implementation

end.
