unit tie;

{$include sdkconfig.inc}

interface

const
  XCHAL_CP_NUM = 1;
  XCHAL_CP_MAX = 1;
  XCHAL_CP_MASK = $01;
  XCHAL_CP_PORT_MASK = $00;
  XCHAL_CP0_NAME = 'FPU';
  //XCHAL_CP0_IDENT = FPU;
  XCHAL_CP0_SA_SIZE = 72;
  XCHAL_CP0_SA_ALIGN = 4;
  XCHAL_CP_ID_FPU = 0;
  XCHAL_CP1_SA_SIZE = 0;
  XCHAL_CP1_SA_ALIGN = 1;
  XCHAL_CP2_SA_SIZE = 0;
  XCHAL_CP2_SA_ALIGN = 1;
  XCHAL_CP3_SA_SIZE = 0;
  XCHAL_CP3_SA_ALIGN = 1;
  XCHAL_CP4_SA_SIZE = 0;
  XCHAL_CP4_SA_ALIGN = 1;
  XCHAL_CP5_SA_SIZE = 0;
  XCHAL_CP5_SA_ALIGN = 1;
  XCHAL_CP6_SA_SIZE = 0;
  XCHAL_CP6_SA_ALIGN = 1;
  XCHAL_CP7_SA_SIZE = 0;
  XCHAL_CP7_SA_ALIGN = 1;
  XCHAL_NCP_SA_SIZE = 48;
  XCHAL_NCP_SA_ALIGN = 4;
  XCHAL_TOTAL_SA_SIZE = 128;
  XCHAL_TOTAL_SA_ALIGN = 4;
  XCHAL_NCP_SA_NUM = 12;
  XCHAL_CP0_SA_NUM = 18;
  XCHAL_CP1_SA_NUM = 0;
  XCHAL_CP2_SA_NUM = 0;
  XCHAL_CP3_SA_NUM = 0;
  XCHAL_CP4_SA_NUM = 0;
  XCHAL_CP5_SA_NUM = 0;
  XCHAL_CP6_SA_NUM = 0;
  XCHAL_CP7_SA_NUM = 0;

implementation


end.
